apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app
  namespace: beta
spec:
  selector:
    matchLabels:
      app: alpine-app
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
      - name: alpine-app
        image: nginx:latest

