# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: alpine-app
#   namespace: app
# spec:
#   selector:
#     matchLabels:
#       app: alpine-app
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: alpine-app
#     spec:
#       containers:
#       - name: alpine-app
#         image: nginx:1.21

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: alpine-app-prod-service
#   namespace: app
# spec:
#   selector:
#     app: alpine-app
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 80
  