apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beta-environment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nukezzzz/ArgoCD.git
    targetRevision: beta
    path: ./environments/beta
  destination:
    server: https://kubernetes.default.svc
    namespace: beta
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true